ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: >
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" &&\
      brew install rbenv postgres && brew services start postgresql &&\
      rbenv install &&\
      gem install bundler &&\
      bundle install
github:
    prebuilds:
        pullRequestsFromForks: true