ports:
  - port: 3000
    onOpen: open-preview
tasks:
  - init: >
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
github:
    prebuilds:
        pullRequestsFromForks: true